version: '3.7'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:2.6.2
    ports:
      - '5000:5000'
  app:
    build: .
    depends_on:
      - mlflow
    ports:
      - '8080:8080'
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
